### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by DaiWeiKIB** [Kinggerm/Traversome#11]
Dear @Kinggerm 

Thank you for your outstanding contribution for this program . 

When I running with data assembled form Flye , and generate it's alignment by using minigraph. The Traversome report an error as follows.

`traversome (v.0.0.6.3): genomic isomer frequency estimator

Python 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:29:00) [GCC 9.4.0]
PLATFORM:  Linux localhost.localdomain 4.18.0-348.el8.x86_64 #1 SMP Tue Oct 19 15:14:17 UTC 2021 x86_64 x86_64
WORKDIR:   /home/daiwei/mitgenome/04/2.27/flye4
COMMAND:   /home/daiwei/miniconda3/envs/ts/bin/traversome mc -g /home/daiwei/mitgenome/04/2.27/flye4/assembly_graph.gfa -a /home/daiwei/mitgenome/04/2.27/flye4/assembly_graph_out.gaf -o /home/daiwei/mitgenome/04/2.27/flye4/TS37

2022-03-07-11:22:25.98 |              AssemblySimple.py | __init__                       | Parsing graph (GFA) to Assembly object
2022-03-07-11:22:25.99 |           GraphAlignRecords.py | __init__                       | Parsing alignment (GAF) to GraphAlignRecords object
2022-03-07-11:22:25.99 |                    __main__.py | mc                             | 
Traceback (most recent call last):

  File "/home/daiwei/miniconda3/envs/ts/bin/traversome", line 33, in <module>
    sys.exit(load_entry_point('traversome', 'console_scripts', 'traversome')())
    │   │    └ <function importlib_load_entry_point at 0x7ff9e014fd90>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/daiwei/miniconda3/envs/ts/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           │           │      │       └ {}
           │           │      └ ()
           │           └ <typer.main.Typer object at 0x7ff9dec8a5c0>
           └ <function get_command at 0x7ff9dea30dc0>
  File "/home/daiwei/miniconda3/envs/ts/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7ff9de9f48b0>
           └ <TyperGroup main>
  File "/home/daiwei/miniconda3/envs/ts/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7ff9deec3610>
         │    └ <function MultiCommand.invoke at 0x7ff9de9f5900>
         └ <TyperGroup main>
  File "/home/daiwei/miniconda3/envs/ts/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7ff9dea38f70>
           │               │       │       └ <function Command.invoke at 0x7ff9de9f5360>
           │               │       └ <TyperCommand mc>
           │               └ <click.core.Context object at 0x7ff9dea38f70>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7ff9dea32320>
  File "/home/daiwei/miniconda3/envs/ts/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'graph_file': '/home/daiwei/mitgenome/04/2.27/flye4/assembly_graph.gfa', 'alignment_file': '/home/daiwei/mitgenome/04/2.27/f...
           │   │      │    │           └ <click.core.Context object at 0x7ff9dea38f70>
           │   │      │    └ <function mc at 0x7ff9dea32050>
           │   │      └ <TyperCommand mc>
           │   └ <function Context.invoke at 0x7ff9de9f40d0>
           └ <click.core.Context object at 0x7ff9dea38f70>
  File "/home/daiwei/miniconda3/envs/ts/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'graph_file': '/home/daiwei/mitgenome/04/2.27/flye4/assembly_graph.gfa', 'alignment_file': '/home/daiwei/mitgenome/04/2.27/f...
                       └ ()
  File "/home/daiwei/miniconda3/envs/ts/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
           │          └ {'graph_file': PosixPath('/home/daiwei/mitgenome/04/2.27/flye4/assembly_graph.gfa'), 'alignment_file': PosixPath('/home/daiwe...
           └ <function mc at 0x7ff9dea31a20>

> File "/home/daiwei/traversome/traversome/__main__.py", line 235, in mc
    traverser.run(
    │         └ <function Traversome.run at 0x7ff614749b40>
    └ <traversome.traversome.Traversome object at 0x7ff9dea3ab00>

  File "/home/daiwei/traversome/traversome/traversome.py", line 93, in run
    self.alignment = GraphAlignRecords(
    │    │           └ <class 'traversome.GraphAlignRecords.GraphAlignRecords'>
    │    └ None
    └ <traversome.traversome.Traversome object at 0x7ff9dea3ab00>

  File "/home/daiwei/traversome/traversome/GraphAlignRecords.py", line 176, in __init__
    self.parse_alignment_file()
    │    └ <function GraphAlignRecords.parse_alignment_file at 0x7ff6273d7250>
    └ <traversome.GraphAlignRecords.GraphAlignRecords object at 0x7ff9dea38700>

  File "/home/daiwei/traversome/traversome/GraphAlignRecords.py", line 186, in parse_alignment_file
    gaf = GAFRecord(line_split, parse_cigar=self.parse_cigar)
          │         │                       │    └ False
          │         │                       └ <traversome.GraphAlignRecords.GraphAlignRecords object at 0x7ff9dea38700>
          │         └ ['[M::main::0.003*2.77] loaded the graph from "/home/daiwei/mitgenome/04/2.27/flye4/assembly_graph.gfa"']
          └ <class 'traversome.GraphAlignRecords.GAFRecord'>

  File "/home/daiwei/traversome/traversome/GraphAlignRecords.py", line 27, in __init__
    self.query_len = int(record_line_split[1])  # q_len or q_aligned_len, not specified in GAF doc, can be tested
    │                    └ ['[M::main::0.003*2.77] loaded the graph from "/home/daiwei/mitgenome/04/2.27/flye4/assembly_graph.gfa"']
    └ <traversome.GraphAlignRecords.GAFRecord object at 0x7ff61473f430>

IndexError: list index out of range
2022-03-07-11:22:26.01 |                    __main__.py | mc                             | Total cost 14.1282`

When I change my data set the error seems still remain.

I'd like to ask you for some advice . Thanks

**Comment by JianjunJin** [comment]
Hi Wei, I'm very sorry for the long delay. I switched to another project for a long time.

It seems to be some non-tab lines in the minigraph-generated gaf file. I have only tested results with GraphAligner, which is now the default of Traversome.
If you are still working on this dataset, please upgrade Traversome to the latest version and use GraphAligner. Otherwise, I would close the current issue.
